name: risto
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  about:
    path: about
  core:
    path: core
  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  search:
    path: search

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
