name: search
description: "A new Flutter package project."
publish_to: "none"

version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.7.1
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  mocktail: ^1.0.1

flutter:
