name: core
description: "A new Flutter package project."
publish_to: "none"

version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  about:
    path: ../about
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_crashlytics: ^4.3.10
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get_it: ^8.2.0
  google_fonts: ^6.3.1
  http: ^1.5.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1

flutter:
