name: about
description: "A new Flutter package project."

publish_to: "none"

version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  firebase_analytics: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
