// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUtSyiJaMb3GQAcEKJZ2telUvkpk3Dbe4',
    appId: '1:122227957795:web:96a9dc6af2759d2f3d1196',
    messagingSenderId: '122227957795',
    projectId: 'risto-8b6c5',
    authDomain: 'risto-8b6c5.firebaseapp.com',
    storageBucket: 'risto-8b6c5.firebasestorage.app',
    measurementId: 'G-7T5EKTVEDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBafsA4dY4_Wot1wGRQ-dXFjwmX3EJMHS8',
    appId: '1:122227957795:android:056a358f1bfb786d3d1196',
    messagingSenderId: '122227957795',
    projectId: 'risto-8b6c5',
    storageBucket: 'risto-8b6c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxwBFbb476y7eHxSoFdocPuxtnvDTMjKg',
    appId: '1:122227957795:ios:dc029c09cd3a11ea3d1196',
    messagingSenderId: '122227957795',
    projectId: 'risto-8b6c5',
    storageBucket: 'risto-8b6c5.firebasestorage.app',
    iosBundleId: 'com.codesynesia.risto',
  );
}
